### ISSUE TITLE
Laravel Call to a member function getBody() on string

### ISSUE THREAD

**Issue by imrantune** [Ibracilinks/OrangeMoney#1]
Hi @Ibraci 
 Its very good effort,I have some facing problem with Laravel integration details below 

`vendor\ibracilinks\orange-money\src\OrangeMoney.php:21`

```
{

    private $api;

    /**

     * @var string or null

     */

    private  $token;

 

    public function __construct(array $config = [])

    {

       $this->api = new Api();

    }

 

    public function getAccesToken()

    {

        $rep = $this->api->getToken();
         
        /// Getting this line error
        $data= json_decode((string)$rep->getBody(),true);

        $this->token=$data["access_token"];

 

        return $data;

    }

 

    public function webPayment($data)

    {

        $dt= $this->getAccesToken();

        $rep = $this->api->Payment($this->token,$data);

 

        if (is_object($rep)) {

            $data = json_decode((string)$rep->getBody(), true);

            return $data;

        } elseif (is_string($rep)) {

            return $rep;
```

**Comment by slydesign1** [comment]
hello, i hope you are fine i got the same error

**Comment by slydesign1** [comment]
> Hi @Ibraci
> Its very good effort,I have some facing problem with Laravel integration details below
> 
> `vendor\ibracilinks\orange-money\src\OrangeMoney.php:21`
> 
> ```
> {
> 
>     private $api;
> 
>     /**
> 
>      * @var string or null
> 
>      */
> 
>     private  $token;
> 
>  
> 
>     public function __construct(array $config = [])
> 
>     {
> 
>        $this->api = new Api();
> 
>     }
> 
>  
> 
>     public function getAccesToken()
> 
>     {
> 
>         $rep = $this->api->getToken();
>          
>         /// Getting this line error
>         $data= json_decode((string)$rep->getBody(),true);
> 
>         $this->token=$data["access_token"];
> 
>  
> 
>         return $data;
> 
>     }
> 
>  
> 
>     public function webPayment($data)
> 
>     {
> 
>         $dt= $this->getAccesToken();
> 
>         $rep = $this->api->Payment($this->token,$data);
> 
>  
> 
>         if (is_object($rep)) {
> 
>             $data = json_decode((string)$rep->getBody(), true);
> 
>             return $data;
> 
>         } elseif (is_string($rep)) {
> 
>             return $rep;
> ```

you need to change your currency it will be working AND add your 'Authorization' in the api.php
